name: Deploy

on:
  push:
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set deployment target
        id: set-target
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "host=curate.fileopia.com" >> $GITHUB_OUTPUT
            echo "user=fileopia-curate" >> $GITHUB_OUTPUT
            echo "port=3000" >> $GITHUB_OUTPUT
          else
            echo "host=curate-dev.fileopia.com" >> $GITHUB_OUTPUT
            echo "user=fileopia-curate-dev" >> $GITHUB_OUTPUT
            echo "port=3001" >> $GITHUB_OUTPUT
          fi
          
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -rf .next
          rm -rf .next/cache
          npm cache clean --force
          npm install
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          
      - name: Build
        run: |
          NODE_OPTIONS="--max-old-space-size=4096" npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ steps.set-target.outputs.user }}
          key: ${{ secrets.SSH_KEY }}
          envs: MONGODB_URI,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,CLERK_SECRET_KEY
          script: |
            cd ~/htdocs/${{ steps.set-target.outputs.host }}
            git pull
            echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}" > .env.production
            echo "CLERK_SECRET_KEY=${CLERK_SECRET_KEY}" >> .env.production
            echo "MONGODB_URI=${MONGODB_URI}" >> .env.production
            npm ci
            rm -rf .next
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            PORT=${{ steps.set-target.outputs.port }} pm2 reload ${{ steps.set-target.outputs.host }} || PORT=${{ steps.set-target.outputs.port }} pm2 start npm --name "${{ steps.set-target.outputs.host }}" -- start
              