name: Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set deployment target
      id: set-target
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "host=favely.net" >> $GITHUB_OUTPUT
          echo "user=favely" >> $GITHUB_OUTPUT
        else
          echo "host=curate-dev.fileopia.com" >> $GITHUB_OUTPUT
          echo "user=fileopia-curate-dev" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ steps.set-target.outputs.user }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ steps.set-target.outputs.user }}/htdocs/${{ steps.set-target.outputs.host }}
          git pull
          npm install
          npm run build
          pm2 reload ${{ steps.set-target.outputs.host }}
              