name: Deploy Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment target
        id: set-target
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "host=curate.fileopia.com" >> $GITHUB_OUTPUT
            echo "user=fileopia-curate" >> $GITHUB_OUTPUT
          else
            echo "host=curate-dev.fileopia.com" >> $GITHUB_OUTPUT
            echo "user=fileopia-curate-dev" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ steps.set-target.outputs.user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Starting deployment..."
            cd ~/htdocs/${{ steps.set-target.outputs.host }}
            
            # Pull latest changes
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            
            # Install and build
            npm install
            npm run build
            
            # Restart the application
            pm2 restart ${{ steps.set-target.outputs.host }} || pm2 start "npm start" --name "${{ steps.set-target.outputs.host }}"
            
            echo "Deployment complete!"

      - name: Verify deployment
        run: |
          echo "Waiting for application to start..."
          sleep 45  # Increased wait time
          for i in {1..3}; do
            if curl -sSfv https://${{ steps.set-target.outputs.host }}; then
              echo "Deployment verified successfully"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
          echo "Deployment verification failed"
          curl -v https://${{ steps.set-target.outputs.host }}
          exit 1
              