name: Deploy

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    
    - name: Set deployment target
      id: set-target
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "host=favely.net" >> $GITHUB_OUTPUT
          echo "user=favely" >> $GITHUB_OUTPUT
        else
          echo "host=curate-dev.fileopia.com" >> $GITHUB_OUTPUT
          echo "user=fileopia-curate-dev" >> $GITHUB_OUTPUT
        fi
    
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ steps.set-target.outputs.user }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          cd /home/${{ steps.set-target.outputs.user }}/htdocs/${{ steps.set-target.outputs.host }}
          
          # Stop the application
          pm2 delete ${{ steps.set-target.outputs.host }} || true
          
          # Stash any local changes
          git stash
          
          # Pull latest changes
          git pull origin ${{ github.ref_name }}
          
          # Install dependencies
          npm ci
          
          # Build the application
          npm run build
          
          # Start the application
          pm2 start ecosystem.config.js
          pm2 save
              